version: '3'

services:
  rplumber:
    build: .
    container_name: rplumber
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
    ports:
      - "8000:8000"